[feat] : 쪽지 상세보기 기능 추가, notification type 정리
hanaro4-dIA/dia_pb_fe pull request #94
Opened 2024-11-22 10:30 UTC by larchlarix

## #️⃣ 이슈 번호 

> #93 

## 💻 작업 내용

> 쪽지 상세보기 기능 추가
   notification type 정리

2024-11-24 14:21 UTC, KyoungEun-creator requested changes
고생많으셨어용!! 
ConsultationRecord라고 타입 정의하신 거 TConsultationRecordProps 라고 재정의만 해주시면 될 것 같습니다~~!👍👍

2024-11-24 14:21 UTC, KyoungEun-creator commented on src/components/NotiHistory.tsx
>  type ConsultationRecord = {
타입에는 맨앞에 T를 붙이고, 맨뒤에 Props를 붙이는 것으로 통일해요~~!

2024-11-25 02:19 UTC, larchlarix commented on src/components/NotiHistory.tsx
>  type ConsultationRecord = {
type ConsultationRecord 삭제
type Customer -> TCustomersProps 변경했습니다~

2024-11-25 02:21 UTC, KyoungEun-creator commented
꼼꼼한 확인 감사합니다!! 고생하셨어용!!👍👍

2024-11-25 02:21 UTC, merged